/** Local-business search terms used when a country crawl is not given explicit keywords. */
export const DEFAULT_INDUSTRIES: readonly string[] = [
  'dentist',
  'medical clinic',
  'physiotherapy clinic',
  'chiropractor',
  'veterinary clinic',
  'aesthetic clinic',
  'hair salon',
  'beauty salon',
  'spa',
  'gym',
  'yoga studio',
  'restaurant',
  'cafe',
  'bakery',
  'hotel',
  'real estate agency',
  'law firm',
  'accounting firm',
  'insurance agency',
  'car repair',
  'car dealer',
  'plumber',
  'electrician',
  'interior design',
  'cleaning service',
  'tuition centre',
  'language school',
  'driving school',
  'wedding planner',
  'florist',
];
