// Regenerates src/discovery/cities.generated.ts from GeoNames dumps (CC BY 4.0, geonames.org).
// Usage: node scripts/generate-cities.mjs <dir containing cities15000.txt and admin1CodesASCII.txt>
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = process.argv[2];
if (!dir) {
  console.error('usage: node scripts/generate-cities.mjs <geonames-dir>');
  process.exit(1);
}

// Municipality-level feature codes. PPL/PPLX in these countries are mostly suburbs or estates,
// except in Malaysia where most towns are plain PPL.
const FEATURE_CODES = {
  JP: new Set(['PPLC', 'PPLA', 'PPLA2']),
  MY: new Set(['PPLC', 'PPLA', 'PPLA2', 'PPL']),
};

const admin1 = new Map();
for (const line of fs.readFileSync(path.join(dir, 'admin1CodesASCII.txt'), 'utf8').split(/\r?\n/)) {
  const [code, , ascii] = line.split('\t');
  if (code && ascii) admin1.set(code, ascii.trim());
}

const byCountry = { JP: [], MY: [] };
for (const line of fs.readFileSync(path.join(dir, 'cities15000.txt'), 'utf8').split(/\r?\n/)) {
  const c = line.split('\t');
  const cc = c[8];
  if (!byCountry[cc] || !FEATURE_CODES[cc].has(c[7])) continue;
  const name = c[2].trim();
  const region = admin1.get(`${cc}.${c[10]}`) ?? '';
  byCountry[cc].push({ name, region, pop: Number(c[14]) || 0 });
}

function labels(rows) {
  const seen = new Set();
  const out = [];
  for (const r of rows.sort((a, b) => b.pop - a.pop)) {
    const region = r.region.replace(/^(Wilayah Persekutuan|Federal Territory of)\s+/i, '');
    const label = !region || region.toLowerCase() === r.name.toLowerCase() ? r.name : `${r.name}, ${region}`;
    const key = label.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(label);
  }
  return out;
}

const jp = labels(byCountry.JP);
const my = labels(byCountry.MY);
const body = `// Generated by scripts/generate-cities.mjs from GeoNames cities15000 (CC BY 4.0, geonames.org).
// Sorted by population, largest first. Do not edit by hand.

export const JP_CITIES: readonly string[] = ${JSON.stringify(jp, null, 2)};

export const MY_CITIES: readonly string[] = ${JSON.stringify(my, null, 2)};
`;
const out = path.join(path.dirname(fileURLToPath(import.meta.url)), '../src/discovery/cities.generated.ts');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, body);
console.log(`JP ${jp.length}, MY ${my.length} -> ${out}`);
